services:
  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - BOT_TOKEN=${BOT_TOKEN:?}
      - CLIENT_ID=${CLIENT_ID:?}
      - CLIENT_SECRET=${CLIENT_SECRET:?}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - REDIRECT_URI=${REDIRECT_URI:?}
    ports:
      - '8000:8000'

  db:
    # https://github.com/docker-library/docs/blob/master/postgres/README.md
    image: postgres:16
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 30s
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
    expose:
      - '5432'
    healthcheck:
      test: ["CMD", "pg_isready", "--quiet", "--username", "postgres"]
      interval: 2s
      timeout: 1s
      retries: 5
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data

volumes:
  db:
