services:
  app:
    build:
      context: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN:?}
      - CLIENT_ID=${CLIENT_ID:?}
      - CLIENT_SECRET=${CLIENT_SECRET:?}
    ports:
      - '8000:8000'
